apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
type: Opaque
data:
  api-key: c2stcHJvai1IdmxXenVkQnNzM2ppOUZtSkhrVHQyemoxSWJ1MTlXS2V4d1ZXZGJvaS1INUxXY2JxVE5PVThQcF9jYjJTSlVITXFpXzVNTFR5NVQzQmxia0ZKNWVJdTgxMFhCOElSNjZzQ2NSY1YwR1hyN0ktSG41SGJSOW9FMmRLam83SGJEd0k4dGh5SmFZVTBZa2NvQnNtcmVmVXRHWVU4WUE=
