apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
type: Opaque
data:
  api-key: c2stcHJvai1qOW8zYUllTldJckZ6ZWp0aEVMVEV3RDFmMW5Gb3dGSEYwbWptZGJXRzVvRTFGOG52SUdkX0dEcGdPbDNSbUkyOFhDZHNXbWhOY1QzQmxia0ZKcWJUUGxOWUdYR3d5cFJycDF2a0xPRG9hckl1MG1DX1I4dGZNV3FNVnNXeWQ4UUJpM01uQVYwa21NdTR2UU5BRmREbE5PYUpqNEE=
